version: '3'
services:
  # MongoDB Service
  mongo:
    image: mongo:5.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - app-network

  # Node.js API Service
  api:
    build:
      context: ./backend
    container_name: node_api
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      MONGO_URL: mongodb://mongodb:27017/zoompoint  # Changed to dictionary style
      PORT: 3000                                      # Changed to dictionary style
    networks:
      - app-network

  # React Frontend Service
  frontend:
    build:
      context: ./frontend
    container_name: react_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - api
    environment:
      REACT_APP_API_URL: http://node_api:3000         # Changed to dictionary style
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge
