version: '3'
services:
  # MongoDB Service
  mongo:
    image: mongo:5.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # Node.js API Service
  api:
    build:
      context: ./backend   # Path to your Node.js app
    container_name: node_api
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongodb:27017/zoompoint  # Connection to MongoDB

  # React Frontend Service
  frontend:
    build:
      context: ./frontend  # Path to your React app
    container_name: react_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - api

volumes:
  mongo_data:
